---
- hosts: Jenkins-Master
  become: yes
  tasks:

    - name: ensure python-certbot-nginx is installed
      apt:
        name: python-certbot-nginx
        state: present

    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest

    - name: start nginx
      service:
          name: nginx
          state: started
~                        