---
apiVersion: apps/v1beta1
kind: Service
metadata:
  name: ej
  namespace: $K8S_NAMESPACE
  labels:
    app.kubernetes.io/name: ej
spec:
  type: NodePort
  ports:
    - name: ej-http
      port: 5280
      targetPort: 5280
      protocol: TCP
    - name: ej-c2s
      port: 5222
      targetPort: 5222
      nodePort: 30002
      protocol: TCP
    - name: ej-s2s
      port: 5269
      targetPort: 5269
      nodePort: 30003
      protocol: TCP
  selector:
    app.kubernetes.io/name: ej
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ej
  namespace: $K8S_NAMESPACE
  labels:
    app.kubernetes.io/name: ej
spec:
  replicas: $K8S_DEPLOY_REPLICAS
  selector:
    matchLabels:
      app.kubernetes.io/name: ej
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ej
        app.kubernetes.io/version: $K8S_APP_VERSION
        app.kubernetes.io/component: ejabberd
        app.kubernetes.io/part-of: chat
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - ej
                - ws
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: prepare-certs
          image: frapsoft/openssl
          command:
          - /bin/sh
          - "-c"
          - "cat /key/tls.key > /certs/server.pem && cat /crt/tls.crt >> /certs/server.pem && openssl dhparam -out /certs/dhparams.pem 2048"
          volumeMounts:
          - name: crt
            mountPath: /crt/tls.crt
            subPath: tls.crt
            readOnly: true
          - name: key
            mountPath: /key/tls.key
            subPath: tls.key
            readOnly: true
          - name: certs
            mountPath: /certs
        - name: prepare-configs
          image: busybox
          env:
            - name: DOGSTATSD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
          - /bin/sh
          - -c
          - cp /config-orig/* /config/ && sed -i 's/statsd_host, "127.0.0.1"/statsd_host,  \"'"$DOGSTATSD_HOST_IP"'\"/g' /config/ejabberd.cfg
          volumeMounts:
          - name: certs
            mountPath: /certs
          - name: ej-config
            mountPath: /config
          - name: config-volume
            mountPath: /config-orig
      containers:
        - name: ej
          image: "$K8S_IMAGE"
          imagePullPolicy: Always
          env:
            - name: EJABBERD_COOKIE
              value: "$K8S_EJABBERD_COOKIE"
          ports:
            - name: xmpp-c2s
              containerPort: 5222
              protocol: TCP
            - name: xmpp-s2s
              containerPort: 5269
              protocol: TCP
            - name: http
              containerPort: 5280
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5222
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5222
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "$K8S_RES_REQ_CPU"
              memory: "$K8S_RES_REQ_RAM"
            limits:
              cpu: "$K8S_RES_LIM_CPU"
              memory: "$K8S_RES_LIM_RAM"
          volumeMounts:
          - name: ej-config
            mountPath: /app/etc/ejabberd
          - name: certs
            mountPath: /certs
      imagePullSecrets:
        - name: ucloud
      volumes:
        - name: config-volume
          configMap:
            name: ej
        - name: crt
          secret:
            secretName: $K8S_XMPP_DOMAIN_SECRET_NAME
            items:
            - key: tls.crt
              path: tls.crt
        - name: key
          secret:
            secretName: $K8S_XMPP_DOMAIN_SECRET_NAME
            items:
            - key: tls.key
              path: tls.key
        - name: certs
          emptyDir: {}
        - name: ej-config
          emptyDir: {}
---
